name: Testing
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15-intel, macos-15]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure PDM
        run: pdm config python.use_venv false

      - name: Install dependencies (Windows)
        if: runner.os == 'windows'
        run: pdm install -G dev --without slepc
      - name: Install libomp on macOS
        if: runner.os == 'macOS'
        run: brew install libomp

      - name: Install dependencies (Linux and Mac)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: pdm install -G dev

      - name: Install PETSc and SLEPc (Linux and macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        env:
          PETSC_CONFIGURE_OPTIONS: >
            --download-f2cblaslapack
            --with-debugging=0
        run: |
          pip install petsc petsc4py
          export PETSC_DIR=$(python -c 'import petsc; print(petsc.get_petsc_dir())')
          export PETSC_ARCH=""
          echo "PETSC_DIR=$PETSC_DIR" >> $GITHUB_ENV
          echo "PETSC_ARCH=" >> $GITHUB_ENV
          pip install slepc slepc4py
          echo "SLEPC_DIR=$(python -c 'import slepc; print(slepc.get_slepc_dir())')" >> $GITHUB_ENV
      - name: Test with pytest & generate coverage
        run: 
          pdm test
